# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: maxschremser
google_analytics: GTM-MRG7BQ
gems: [jekyll-paginate,jekyll-gist]

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Maximilian Schremser

description: "Survivalist, Developer, Naturalist"
author:
  name: Maximilian Schremser
  email: maxi@schremser.com
  github: maxschremser
  twitter: maxschremser
  pinterest: maxschremser
  linkedin: maxschremser
  bio: Survivalist, Developer, Naturalist
  email_md5: b2717a8d781fb6b1624fba4015cb59d8

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
